runtime: nodejs20
# FORCING UPLOAD 20260526

env_variables:
  # Supabase PostgreSQL Connection Variable
  DATABASE_URL: "postgresql://postgres:9%21%2F_4X6_NM5xNCa@db.zxeccmqlcwqtpkbyzcdf.supabase.co:5432/postgres"
  
  # App Configuration Settings
  JWT_SECRET: "3a32982656311170749e2aae73c5b33f7784c66e1bc1364e8a35f7f203a5b172d21d290d71da0f39c728cca4eb67a93a0261ae1e925eafceace6210cf22cf0de"
  MAIL_USER: "mruzaffi4812@gmail.com"
  MAIL_PASS: "nxcf xwly tsdb nffa"

handlers:
- url: /api/.*
  script: auto
  secure: always

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /(.*)
  static_files: public/\1
  upload: public/(.*)